import type { Metadata } from "next";
import { Play, IBM_Plex_Mono, JetBrains_Mono } from "next/font/google";
import "./globals.css";

const playFont = Play({
	variable: "--font-play",
	weight: ["400", "700"],
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={`${playFont.variable} ${playFont.variable} antialiased`}>{children}</body>
		</html>
	);
}
